### Advantages of numpy over lists
- less memory
- fast
- convenient

### Importing the packages

In [1]:
import numpy as np
import sys

### The basics

In [2]:
a = np.array([1, 2, 3])
print(a)
print(a.ndim)

[1 2 3]
1


In [3]:
type(a)

numpy.ndarray

In [4]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
2


In [5]:
# Get shape
a.shape

(2, 3)

In [6]:
# Get type
a.dtype

dtype('int32')

In [7]:
# Get size
a.itemsize

4

In [8]:
# Get total size
a.size*a.itemsize

24

In [9]:
b = np.array([1, 2, 3], dtype='int8')

In [10]:
print(b)

[1 2 3]


In [11]:
b.dtype

dtype('int8')

In [12]:
b.size*b.itemsize

3

### Accessing/Changing specific elements, rows, columns, etc

In [13]:
a = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])

In [14]:
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [15]:
a.shape

(2, 6)

In [16]:
# get a specific element [r, c]
a[1, 5]

12

In [17]:
# negative indexing
a[1, -5]

8

In [18]:
# get a specific row
a[1, :]

array([ 7,  8,  9, 10, 11, 12])

In [19]:
# get a specific column
a[:, 0]

array([1, 7])

In [20]:
# getting [startindex : endindex : stepsize]
a[0, 0: 4: 2]

array([1, 3])

In [21]:
a[0, 0: : 2]

array([1, 3, 5])

In [22]:
a[:, 0: : 2]

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [23]:
# changing the values at [row, column]
a[1, 5] = 89
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 89]]


In [24]:
# changing the value of column
a[:, 2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6]
 [ 7  8  2 10 11 89]]


In [25]:
# changing the value of row
a[1, :] = [89, 56, 23, 45, 12, 9]
print(a)

[[ 1  2  1  4  5  6]
 [89 56 23 45 12  9]]


In [26]:
# 3D example
a = np.array([[[1, 2], [34, 67]], [[78, 98], [90, 47]]])
print(a)

[[[ 1  2]
  [34 67]]

 [[78 98]
  [90 47]]]


In [27]:
a.dtype

dtype('int32')

In [28]:
a.ndim

3

In [29]:
a[1, 0, 1]

98

In [30]:
a[0, 1, 1] = 57
print(a)

[[[ 1  2]
  [34 57]]

 [[78 98]
  [90 47]]]


In [31]:
a[:, 1, 1] = 0
print(a)

[[[ 1  2]
  [34  0]]

 [[78 98]
  [90  0]]]


In [32]:
a[:, 1, :] = [45, 89]
print(a)

[[[ 1  2]
  [45 89]]

 [[78 98]
  [45 89]]]


### Initializing different types of arrays

In [33]:
# all 0s matrix
print(np.zeros([2], dtype='int8'))

[0 0]


In [34]:
print(np.zeros([5, 4], dtype='int8'))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [35]:
print(np.zeros([5, 4, 3]))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [36]:
# all 1s matrix
print(np.ones((4, 2, 2)))

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [37]:
# any other number
print(np.full((3, 1, 2), 9))

[[[9 9]]

 [[9 9]]

 [[9 9]]]


In [38]:
# any other number (full_like)
np.full_like(a, 5)

array([[[5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5]]])

In [39]:
# random decimal numbers
print(np.random.rand(4, 2))

[[0.37984083 0.96184053]
 [0.13475167 0.06903223]
 [0.27972669 0.53174122]
 [0.45097605 0.82735443]]


In [40]:
# random decimal numbers in predefined array shape
print(np.random.random_sample(a.shape))

[[[0.59779938 0.44762012]
  [0.82709237 0.10634504]]

 [[0.2559417  0.10738009]
  [0.29342805 0.11971006]]]


In [41]:
# random integer values
print(np.random.randint(10, size=(3, 3)))

[[2 4 0]
 [7 3 5]
 [2 1 2]]


In [42]:
# random integer values in range 
print(np.random.randint(-100, 100, size=(3, 3)))

[[-64  92 -71]
 [ 27  66 -98]
 [-89   3  19]]


In [43]:
# identity matrix
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
print(np.identity(5, int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [45]:
arr = np.array([1, 2, 3])
print(np.repeat(arr, 3))

[1 1 1 2 2 2 3 3 3]


In [46]:
arr = np.array([[1, 2, 3]])
print(np.repeat(arr, 3, axis=0))

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [47]:
arr = np.array([[1, 2, 3]])
print(np.repeat(arr, 3, axis=1))

[[1 1 1 2 2 2 3 3 3]]


In [48]:
# a pattern

o = np.ones([5, 5], dtype='int8')
print(o)

z = np.zeros((3, 3), dtype='int8')
print(z)

z[1, 1] = 9
print(z)

o[1:4, 1:4] = z
print(o)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Copying arrays

In [49]:
a = np.array([1, 2, 3])
b = a
b[0] = 100
print(b)
print(a)

[100   2   3]
[100   2   3]


In [50]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


### Mathematics

In [51]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [52]:
a = a + 2
a

array([3, 4, 5, 6])

In [53]:
a = a + 2
a

array([5, 6, 7, 8])

In [54]:
a += 2
a

array([ 7,  8,  9, 10])

In [55]:
a -= 2
a

array([5, 6, 7, 8])

In [56]:
a *= 2
a

array([10, 12, 14, 16])

In [57]:
a = a / 2
a

array([5., 6., 7., 8.])

In [58]:
b = np.array([1, 0, 1, 0])
print(a + b)

[6. 6. 8. 8.]


In [59]:
(a+b)**2

array([36., 36., 64., 64.])

In [60]:
a ** 3

array([125., 216., 343., 512.])

In [61]:
# take the sin
np.cos(125)

0.7877145121442345

In [62]:
np.cos(5)

0.28366218546322625

In [63]:
np.cos(a)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

In [64]:
# take the sin
np.sin(a)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [65]:
# take the tan
np.tan(a)

array([-3.38051501, -0.29100619,  0.87144798, -6.79971146])

### Linear Algebra

In [66]:
a = np.ones((2, 3))

In [67]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [68]:
b = np.full((3, 2), 7)

In [69]:
b

array([[7, 7],
       [7, 7],
       [7, 7]])

In [70]:
# matrix multipllication
np.matmul(a, b)

array([[21., 21.],
       [21., 21.]])

In [71]:
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
# find the determinant
np.linalg.det(c)

1.0

### Statistics

In [73]:
stats = np.array([[2, 3, 6], [4, 5, 0]])
stats

array([[2, 3, 6],
       [4, 5, 0]])

In [74]:
np.min(stats)

0

In [75]:
np.min(stats, axis=0)

array([2, 3, 0])

In [76]:
np.min(stats, axis=1)

array([2, 0])

In [77]:
np.max(stats)

6

In [78]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [79]:
np.sum(stats)

20

In [80]:
np.sum(stats, axis=0)

array([6, 8, 6])

In [81]:
np.sum(stats, axis=1)

array([11,  9])

### Reorganizing the arrays

In [82]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [83]:
print(arr.reshape(8, 1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [84]:
print(arr.reshape(4, 2))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [85]:
print(arr.reshape(2, 2, 2))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [86]:
# vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
np.vstack([v2, v1])

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [87]:
np.vstack([v1, v1, v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [88]:
# horizontal stack
np.hstack([v1, v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [89]:
# column stack
np.column_stack([v1, v2, v1])

array([[1, 5, 1],
       [2, 6, 2],
       [3, 7, 3],
       [4, 8, 4]])

In [90]:
np.hstack([v1, v1, v2])

array([1, 2, 3, 4, 1, 2, 3, 4, 5, 6, 7, 8])

In [91]:
h1 = np.ones((2, 4), dtype='int16')
h2 = np.zeros((2, 2), dtype='int16')

In [92]:
np.hstack([h1, h2])

array([[1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 0]], dtype=int16)

In [93]:
np.hstack([h2, h2, h1])

array([[0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1]], dtype=int16)

### Miscellaneous

#### Load data from file

In [94]:
arr1 = np.genfromtxt('data.txt', delimiter=',', dtype='int16')
print(arr1)

[[  1  13  21  11 196  75   4]
 [  3  34   6   7   8   0   1]
 [  3  42  12  33 766  75   4]
 [ 55   6   4   3   4   5   6]
 [  1  22  33  11 999  11   2]
 [  1  78   0   1   2   9   8]]


In [95]:
arr2 = arr1.astype('float')
print(arr2)

[[  1.  13.  21.  11. 196.  75.   4.]
 [  3.  34.   6.   7.   8.   0.   1.]
 [  3.  42.  12.  33. 766.  75.   4.]
 [ 55.   6.   4.   3.   4.   5.   6.]
 [  1.  22.  33.  11. 999.  11.   2.]
 [  1.  78.   0.   1.   2.   9.   8.]]


#### Boolean masking & Advanced indexing

In [96]:
arr1 > 50

array([[False, False, False, False,  True,  True, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False],
       [ True, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False],
       [False,  True, False, False, False, False, False]])

In [97]:
arr2 >= 30

array([[False, False, False, False,  True,  True, False],
       [False,  True, False, False, False, False, False],
       [False,  True, False,  True,  True,  True, False],
       [ True, False, False, False, False, False, False],
       [False, False,  True, False,  True, False, False],
       [False,  True, False, False, False, False, False]])

In [98]:
arr1[arr1 > 30]

array([196,  75,  34,  42,  33, 766,  75,  55,  33, 999,  78], dtype=int16)

In [99]:
# indexing with a list in numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
print(a[[1, 2, 8]])

[2 3 9]


In [100]:
np.any(arr1 > 30, axis = 0)

array([ True,  True,  True,  True,  True,  True, False])

In [101]:
np.any(arr1 > 30, axis = 1)

array([ True,  True,  True,  True,  True,  True])

In [102]:
np.all(arr1 > 30, axis = 1)

array([False, False, False, False, False, False])

In [103]:
(arr1 > 10) & (arr1 <100)

array([[False,  True,  True,  True, False,  True, False],
       [False,  True, False, False, False, False, False],
       [False,  True,  True,  True, False,  True, False],
       [ True, False, False, False, False, False, False],
       [False,  True,  True,  True, False,  True, False],
       [False,  True, False, False, False, False, False]])

In [104]:
~(arr1 > 10) & (arr1 <100)

array([[ True, False, False, False, False, False,  True],
       [ True, False,  True,  True,  True,  True,  True],
       [ True, False, False, False, False, False,  True],
       [False,  True,  True,  True,  True,  True,  True],
       [ True, False, False, False, False, False,  True],
       [ True, False,  True,  True,  True,  True,  True]])